CREATE INDEX "shots_speaker_character_id_idx" ON "shots" USING btree ("speaker_character_id");--> statement-breakpoint
CREATE INDEX "usage_log_series_id_idx" ON "usage_log" USING btree ("series_id");--> statement-breakpoint
CREATE INDEX "usage_log_episode_id_idx" ON "usage_log" USING btree ("episode_id");--> statement-breakpoint
ALTER POLICY "assets_owner_all" ON "assets" TO authenticated USING (exists (select 1 from episodes e join series s on s.id = e.series_id where e.id = assets.episode_id and s.user_id = (select auth.uid()))) WITH CHECK (exists (select 1 from episodes e join series s on s.id = e.series_id where e.id = assets.episode_id and s.user_id = (select auth.uid())));--> statement-breakpoint
ALTER POLICY "characters_owner_all" ON "characters" TO authenticated USING (exists (select 1 from series s where s.id = characters.series_id and s.user_id = (select auth.uid()))) WITH CHECK (exists (select 1 from series s where s.id = characters.series_id and s.user_id = (select auth.uid())));--> statement-breakpoint
ALTER POLICY "episodes_owner_all" ON "episodes" TO authenticated USING (exists (select 1 from series s where s.id = episodes.series_id and s.user_id = (select auth.uid()))) WITH CHECK (exists (select 1 from series s where s.id = episodes.series_id and s.user_id = (select auth.uid())));--> statement-breakpoint
ALTER POLICY "renders_owner_all" ON "renders" TO authenticated USING (exists (select 1 from episodes e join series s on s.id = e.series_id where e.id = renders.episode_id and s.user_id = (select auth.uid()))) WITH CHECK (exists (select 1 from episodes e join series s on s.id = e.series_id where e.id = renders.episode_id and s.user_id = (select auth.uid())));--> statement-breakpoint
ALTER POLICY "scenes_owner_all" ON "scenes" TO authenticated USING (exists (select 1 from episodes e join series s on s.id = e.series_id where e.id = scenes.episode_id and s.user_id = (select auth.uid()))) WITH CHECK (exists (select 1 from episodes e join series s on s.id = e.series_id where e.id = scenes.episode_id and s.user_id = (select auth.uid())));--> statement-breakpoint
ALTER POLICY "series_owner_all" ON "series" TO authenticated USING (series.user_id = (select auth.uid())) WITH CHECK (series.user_id = (select auth.uid()));--> statement-breakpoint
ALTER POLICY "shots_owner_all" ON "shots" TO authenticated USING (exists (select 1 from scenes sc join episodes e on e.id = sc.episode_id join series s on s.id = e.series_id where sc.id = shots.scene_id and s.user_id = (select auth.uid()))) WITH CHECK (exists (select 1 from scenes sc join episodes e on e.id = sc.episode_id join series s on s.id = e.series_id where sc.id = shots.scene_id and s.user_id = (select auth.uid())));--> statement-breakpoint
ALTER POLICY "usage_log_owner_all" ON "usage_log" TO authenticated USING (usage_log.user_id = (select auth.uid())) WITH CHECK (usage_log.user_id = (select auth.uid()));