import { NonRetriableError } from 'inngest';
import { eq } from 'drizzle-orm';
import { db } from '@/lib/db';
import { episodes, series } from '@/lib/db/schema';
import type { RunStage } from '@/lib/db/schema';
import { generateBible } from '@/lib/ai/bible';
import { generateScript } from '@/lib/ai/script';
import { generateStoryboard } from '@/lib/ai/storyboard';
import { generateMissingPortraits } from '@/lib/characters/portraits';
import { startAssembly } from '@/lib/data/assemble';
import { MAX_INFLIGHT_VIDEO_JOBS } from '@/lib/data/generation';
import {
  gateSeconds,
  isGated,
  loadRunForJob,
  nextStage,
  recordStageResult,
  refreshSpend,
  shotProgress,
  updateRun,
} from '@/lib/data/runs';
import {
  loadEpisode,
  parseBible,
  parseScript,
  persistBible,
  persistScript,
} from '@/lib/data/series';
import { persistStoryboard } from '@/lib/data/storyboard';
import { latestRender } from '@/lib/data/render';
import { getLlmProvider, getVideoProvider } from '@/lib/providers';
import { log } from '@/lib/log';
import { episodeGenerateEventId, inngest } from '../client';

/**
 * The unattended run: one prompt in, a finished film out.
 *
 * This function orchestrates the six phases rather than reimplementing them.
 * Every stage below calls the same `generate…`/`persist…` pair the manual UI
 * calls, so a run and a hand-built series produce identical rows — which is what
 * lets a run stop halfway and leave something a human can pick up and finish by
 * hand.
 *
 * Two properties are load-bearing:
 *
 * - **Gates are skippable, not optional.** At `bible` and `storyboard` the run
 *   pauses and waits for a decision *or* a countdown. Walk away and it finishes;
 *   stay and you can stop a wrong premise before it becomes thirty clips. A gate
 *   that blocked forever would defeat the point; no gate at all would mean the
 *   whole budget is spent before the first thing you can judge appears.
 *
 * - **The expensive stage is polled, not awaited.** Shot generation fans out to
 *   per-shot jobs with their own retries and concurrency cap. This waits on the
 *   *rows*, so a shot retried automatically, or regenerated by hand from the
 *   review board mid-run, is accounted for correctly.
 */

/**
 * How long to wait for every shot to settle.
 *
 * Derived from the work rather than fixed. A flat thirty minutes was fine for a
 * sixty-second short and would abandon a three-minute film at about the halfway
 * mark: thirty-six clips three at a time is a twenty-five minute job before any
 * retries, and a retry costs another poll cycle. Timing out a run that is still
 * making progress is the worst outcome available — the money is spent and the
 * film is not finished.
 *
 * Budgets four minutes per batch against a nominal two, so a slow provider or a
 * couple of retries do not end the run, plus a floor for very short films.
 */
const SHOT_WAIT_SECONDS = 15;
const MINUTES_PER_BATCH = 4;

function shotWaitAttempts(shotCount: number, concurrency: number): number {
  const batches = Math.ceil(Math.max(1, shotCount) / Math.max(1, concurrency));
  const minutes = Math.max(20, batches * MINUTES_PER_BATCH);
  return Math.ceil((minutes * 60) / SHOT_WAIT_SECONDS);
}

/** Assembly is one encode, but a cloud renderer queues. */
const RENDER_WAIT_ATTEMPTS = 60;
const RENDER_WAIT_SECONDS = 10;

export const autorun = inngest.createFunction(
  {
    id: 'run-autopilot',
    name: 'Prompt to film',
    // One run at a time per user. Two unattended runs would race each other for
    // the per-project video slots and make both look stalled.
    concurrency: { limit: 1, key: 'event.data.userId' },
    retries: 2,
  },
  { event: 'run/start.requested' },
  async ({ event, step }) => {
    const { userId, runId } = event.data;
    const context = { userId, runId, operation: 'run.autopilot' };

    /**
     * Runs the next stage, or stops.
     *
     * Written as a loop over the stage list rather than a chain of awaits so
     * that resuming a crashed run, or one continued from a gate, re-enters at
     * whatever stage the row says — the database is the program counter.
     */
    for (let guard = 0; guard < 20; guard++) {
      const run = await step.run(`load-${guard}`, async () => {
        const row = await loadRunForJob(runId);
        return {
          stage: row.stage,
          status: row.status,
          seriesId: row.seriesId,
          prompt: row.prompt,
          targetSeconds: row.targetSeconds,
        };
      });

      if (run.status === 'cancelled') {
        log.info('run cancelled', { ...context, stage: run.stage });
        return { runId, stopped: 'cancelled' as const, stage: run.stage };
      }
      if (run.stage === 'done') {
        await step.run('complete', () =>
          updateRun(runId, { status: 'completed', gateExpiresAt: null }),
        );
        return { runId, completed: true as const };
      }

      /* -- gate ---------------------------------------------------------- */

      // Gates sit *before* the stage that follows them, so what is being judged
      // is work that already exists.
      if (isGated(previousStage(run.stage)) && run.status !== 'running') {
        const seconds = gateSeconds();

        await step.run(`gate-open-${run.stage}`, () =>
          updateRun(runId, {
            status: 'awaiting_gate',
            gateExpiresAt: new Date(Date.now() + seconds * 1000),
          }),
        );

        const decision = await step.waitForEvent(`gate-${run.stage}`, {
          event: 'run/gate.resolved',
          timeout: `${seconds}s`,
          if: `async.data.runId == "${runId}"`,
        });

        // No decision means the countdown expired, which is a decision: continue.
        if (decision?.data.action === 'stop') {
          await step.run(`gate-stop-${run.stage}`, () =>
            updateRun(runId, { status: 'cancelled', gateExpiresAt: null }),
          );
          return { runId, stopped: 'gate' as const, stage: run.stage };
        }
      }

      await step.run(`begin-${run.stage}`, () =>
        updateRun(runId, { status: 'running', gateExpiresAt: null }),
      );

      /* -- the stage itself ---------------------------------------------- */

      const seriesId = await step.run(`stage-${run.stage}-${guard}`, async () => {
        switch (run.stage) {
          case 'bible':
            return runBibleStage(runId, userId, run.prompt, run.targetSeconds);
          case 'cast':
            return runCastStage(runId, userId, requireSeries(run.seriesId));
          case 'script':
            return runScriptStage(runId, userId, requireSeries(run.seriesId));
          case 'storyboard':
            return runStoryboardStage(runId, userId, requireSeries(run.seriesId));
          case 'shots':
            return runShotsStage(runId, userId, requireSeries(run.seriesId));
          case 'assemble':
            return runAssembleStage(runId, userId, requireSeries(run.seriesId));
          default:
            return run.seriesId;
        }
      });

      /* -- waiting stages ------------------------------------------------ */

      if (run.stage === 'shots') {
        const episodeId = await step.run('shots-episode', () =>
          firstEpisodeId(requireSeries(seriesId)),
        );

        // How many shots there actually are, rather than how many were planned:
        // the storyboard may have landed anywhere in its range.
        const attempts = await step.run('shots-budget', async () => {
          const progress = await shotProgress(episodeId);
          return shotWaitAttempts(progress.shotsTotal, MAX_INFLIGHT_VIDEO_JOBS);
        });

        let settled = false;
        for (let attempt = 0; attempt < attempts && !settled; attempt++) {
          await step.sleep(`shots-wait-${attempt}`, `${SHOT_WAIT_SECONDS}s`);
          settled = await step.run(`shots-poll-${attempt}`, async () => {
            const progress = await shotProgress(episodeId);
            await refreshSpend(runId);
            return progress.settled;
          });
        }

        if (!settled) {
          await step.run('shots-timeout', () =>
            updateRun(runId, {
              status: 'failed',
              error:
                'Shot generation did not finish in time. The clips that did land are on the ' +
                'review board — generate the rest from there.',
            }),
          );
          return { runId, stopped: 'timeout' as const, stage: 'shots' as const };
        }
      }

      if (run.stage === 'assemble') {
        let ready = false;
        for (let attempt = 0; attempt < RENDER_WAIT_ATTEMPTS && !ready; attempt++) {
          await step.sleep(`render-wait-${attempt}`, `${RENDER_WAIT_SECONDS}s`);
          ready = await step.run(`render-poll-${attempt}`, async () => {
            const render = await latestRender(userId, await firstEpisodeId(requireSeries(seriesId)));
            return render?.status === 'ready';
          });
        }
      }

      await step.run(`advance-${run.stage}-${guard}`, async () => {
        await refreshSpend(runId);
        return updateRun(runId, {
          stage: nextStage(run.stage),
          status: 'pending',
          ...(seriesId ? { seriesId } : {}),
        });
      });
    }

    await step.run('guard-exhausted', () =>
      updateRun(runId, { status: 'failed', error: 'The run made no progress and was stopped.' }),
    );
    return { runId, stopped: 'guard' as const };
  },
);

/* -------------------------------------------------------------------------- */
/* Stages                                                                     */
/* -------------------------------------------------------------------------- */

function requireSeries(seriesId: string | null | undefined): string {
  if (!seriesId) {
    throw new NonRetriableError('This run has no series yet — the bible stage did not finish.');
  }
  return seriesId;
}

function previousStage(stage: RunStage): RunStage {
  const order: RunStage[] = ['bible', 'cast', 'script', 'storyboard', 'shots', 'assemble', 'done'];
  const index = order.indexOf(stage);
  return order[index - 1] ?? 'bible';
}

async function firstEpisodeId(seriesId: string): Promise<string> {
  const [row] = await db()
    .select({ id: episodes.id })
    .from(episodes)
    .where(eq(episodes.seriesId, seriesId));
  if (!row) throw new NonRetriableError('This run has no episode to work on.');
  return row.id;
}

/** Creates the series and develops the bible, cast and episode stubs. */
async function runBibleStage(
  runId: string,
  userId: string,
  prompt: string,
  targetSeconds: number,
): Promise<string> {
  const [row] = await db()
    .insert(series)
    .values({
      userId,
      // Placeholders until the bible names the show.
      title: prompt.slice(0, 60),
      logline: prompt,
      episodeTargetCount: 1,
      episodeTargetSeconds: targetSeconds,
      status: 'draft',
    })
    .returning({ id: series.id });

  const seriesId = row!.id;
  await updateRun(runId, { seriesId });

  const result = await generateBible({
    provider: getLlmProvider(),
    input: {
      premise: prompt,
      genre: '',
      tone: '',
      audience: '',
      language: 'en',
      episodeCount: 1,
      episodeSeconds: targetSeconds,
    },
  });

  await persistBible(userId, seriesId, result.data);
  await recordStageResult(runId, 'bible', {
    title: result.data.title,
    logline: result.data.logline,
    characters: result.data.characters.map((c) => c.name),
    costCents: result.usage.costCents,
  });

  return seriesId;
}

/** Draws every character, so the shots can be image-to-video. */
async function runCastStage(runId: string, userId: string, seriesId: string): Promise<string> {
  const result = await generateMissingPortraits(userId, seriesId);

  await recordStageResult(runId, 'cast', {
    generated: result.generated.map((g) => ({ name: g.characterName, stills: g.generated })),
    skipped: result.skipped,
    costCents: result.costCents,
  });

  return seriesId;
}

async function runScriptStage(runId: string, userId: string, seriesId: string): Promise<string> {
  const episodeId = await firstEpisodeId(seriesId);
  const { episode, series: seriesRow } = await loadEpisode(userId, episodeId);

  const bible = parseBible(seriesRow.bible);
  if (!bible) throw new NonRetriableError('The bible stage produced nothing usable.');

  const result = await generateScript({
    provider: getLlmProvider(),
    bible,
    episodeNumber: episode.number,
    episodeSeconds: seriesRow.episodeTargetSeconds,
    language: seriesRow.language,
  });

  await persistScript(userId, episodeId, result.data);
  await recordStageResult(runId, 'script', {
    hook: result.data.hook,
    scenes: result.data.scenes.length,
    costCents: result.usage.costCents,
  });

  return seriesId;
}

async function runStoryboardStage(
  runId: string,
  userId: string,
  seriesId: string,
): Promise<string> {
  const episodeId = await firstEpisodeId(seriesId);
  const { episode, series: seriesRow } = await loadEpisode(userId, episodeId);

  const bible = parseBible(seriesRow.bible);
  const script = parseScript(episode.script);
  if (!bible || !script) {
    throw new NonRetriableError('The script stage produced nothing to storyboard.');
  }

  const video = getVideoProvider();
  const result = await generateStoryboard({
    provider: getLlmProvider(),
    bible,
    script,
    episodeNumber: episode.number,
    episodeSeconds: seriesRow.episodeTargetSeconds,
  });

  const persisted = await persistStoryboard({
    userId,
    episodeId,
    bible,
    script,
    storyboard: result.data,
    episodeSeconds: seriesRow.episodeTargetSeconds,
    clampDuration: (seconds) => video.clampDuration(seconds),
  });

  await recordStageResult(runId, 'storyboard', {
    ...persisted,
    costCents: result.usage.costCents,
  });

  return seriesId;
}

/** Fans out to the per-shot jobs. The supervisor waits on the rows, not this. */
async function runShotsStage(runId: string, userId: string, seriesId: string): Promise<string> {
  const episodeId = await firstEpisodeId(seriesId);

  await inngest.send({
    id: episodeGenerateEventId(episodeId, runId),
    name: 'episode/generate.requested',
    data: { userId, episodeId },
  });

  await recordStageResult(runId, 'shots', { episodeId, fannedOutAt: new Date().toISOString() });
  return seriesId;
}

async function runAssembleStage(
  runId: string,
  userId: string,
  seriesId: string,
): Promise<string> {
  const episodeId = await firstEpisodeId(seriesId);

  try {
    const result = await startAssembly(userId, episodeId);
    await recordStageResult(runId, 'assemble', result);
  } catch (error) {
    // A 409 here means shots failed rather than that assembly is broken. Say
    // which, and leave everything that did generate on the board.
    const message = error instanceof Error ? error.message : String(error);
    await recordStageResult(runId, 'assemble', { refused: message });
    throw new NonRetriableError(message);
  }

  return seriesId;
}
